force-app/main/default/objects/Chat_Bot__c/Chat_Bot__c.object-meta.xml
<CustomObject>
    <label>Chat Bot</label>
    <nameField>
        <displayFormat>CB - {00000}</displayFormat>
        <label>ChatBox Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_Bot__c/fields/Chat_Input__c.field-meta.xml
<CustomField>
    <fullName>Chat_Input__c</fullName>
    <label>Chat Input</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chat_Bot__c/fields/Chat_Predictions__c.field-meta.xml
<CustomField>
    <fullName>Chat_Predictions__c</fullName>
    <label>Chat Predictions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chat_Bot__c/fields/Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Response_Time__c</fullName>
    <label>Response Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChatBotModelController.cls
public class ChatBotModelController{

    @AuraEnabled
    public static void ChatBotInvokeFunctionModel(String ChatBotInput) {

        Long startTime = DateTime.now().getTime();
        String Jsonpayload = '{"sentence": "'+ChatBotInput+'"}';

        functions.Function myFunction = functions.Function.get('SalesforceFunctions.chatbot');
        functions.FunctionInvocation invocation = myFunction.invoke(Jsonpayload);
        String jsonResponse = invocation.getResponse();
        Long endTime = DateTime.now().getTime();
        Long milliseconds = endTime - startTime;

        Chat_Bot__c InsertChatbot = new Chat_Bot__c(Chat_Input__c = ChatBotInput, Chat_Predictions__c = jsonResponse, Response_Time__c =milliseconds );
        insert InsertChatbot; 
    }


}